### ISSUE TITLE
Will break on 2.2

### ISSUE THREAD

**Issue by pogzie** [MooseOnTehLoose/pkd#3]
@MooseOnTehLoose did i get it correctly that this line of code is used to apply the changes to the cluster configuration (ie CIDRs, etc)? Considering 2.2 uses `kubectl create` rather than apply, should we consider its use moving forward?

https://github.com/MooseOnTehLoose/pkd/blob/6e25fa2f0629574abc7826239ad61610ddef66a0/pkd.go#L923

**Comment by MooseOnTehLoose** [comment]
I've updated the code so that it uses kubectl create instead of apply. 

I've also tested and verified with Centos 7.9 on prem and airgap
